---
<<<<<<< HEAD
=======
title: Mahad Qureshi | Product Designer
>>>>>>> origin/master
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
<<<<<<< HEAD
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
=======
email: hello@mahadqureshi.com
description: |
  I'm Mahad. I'm a designer in DC.
baseurl: ''
url: http://yourdomain.com
twitter_username: mahdqureshi
github_username: mahdqureshi
permalink: "/:title"
markdown: kramdown
>>>>>>> origin/master
