# Site settings
title: Mahad Qureshi | Product Designer
email: hello@mahadqureshi.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Mahad. I'm a designer in DC.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mahdqureshi
github_username:  mahdqureshi
permalink: /:title

# Build settings
markdown: kramdown
